---
output: pdf_document
---

\pagenumbering{gobble}

\centering

**Uma introdução à análise explanatória de dados e métodos estatísticos**

**Verão 2017**

\vspace{3mm}

**Projeto**


\ \ 

\ \


\raggedright

\vspace{0.8cm}


* Apresentação de até 25 minutos sobre um dos seguintes projetos:

    * Análise da associação entre função motora e força muscular em pacientes com distrofia muscular de Duchenne: acompanhamento de 4 anos (regressão Beta);
    * Avaliação do Findrisk como instrumento de detecção de diabetes de tipo 2 em um estudo transversal (regressão logística);
    * Análise do perfil sócio demográfico de mulheres usuárias de álcool e outras drogas atendidas no período entre 2002 e 2010 no Centro de Referência em Álcool, Tabaco e Outras Drogas (CRATOD) da cidade de São Paulo (análise de dados categorizados);
    * Avaliação da diferença de gêneros na duração e dispersão do complexo QRS em relação à mortalidade em pacientes com insuficiência cardíaca (análise de sobrevivência --- modelo de Cox);
    * Análise da curvatura da coluna vertebral de mães em função do transporte de seus filhos (regressão normal --- equações de estimação generalizadas); e
    * Previsão de volume de compras de hortaliças pelo varejo paulista (séries temporais).

\vspace{3mm}
    
* No máximo dois grupos por relatório.

\vspace{3mm}

* A apresentação deve conter os tópicos abaixo:

    * contextualizar o problema;
    * enumerar os objetivos;
    * apresentar as principais variáveis;
    * discutir a metodologia escolhida; e
    * citar as conclusões.

\vspace{3mm}

* A preparação do projeto vai ser auxiliada pelos monitores, na monitoria ou por e-mail.

\vspace{3mm}

* Datas: 01/02 (se necessário), 02/02 e 03/02.

\vspace{3mm}

* Nota: avaliação dos tópicos requesitados.








