---
output: pdf_document
---

\pagenumbering{gobble}

\centering

**Uma introdução à análise explanatória de dados e métodos estatísticos**

**Verão 2017**

**Questionário**


\ \ 

\ \


\raggedright

\vspace{0.8cm}

**Sexo**: ( ) M \hspace{0.5mm} ( ) F

\vspace{3mm}

**Idade**: _________

\vspace{3mm}

**Altura**: _________

\vspace{3mm}

**Peso**: _________

\vspace{0.8cm}

**Curso (em que se formou ou que está fazendo)**: _____________________________

\vspace{3mm}

**Trabalha**: ( ) Sim \hspace{0.5mm} ( ) Não

\vspace{3mm}

**Onde mora**: ( ) ZN \hspace{0.5mm} ( ) ZS \hspace{0.5mm} ( ) ZL \hspace{0.5mm} ( ) ZO \hspace{0.5mm} ( ) Centro \hspace{0.5mm} Outro : ______________________

\vspace{3mm}

**Meio de transporte**: ( ) Carro/moto \hspace{0.5mm} ( ) Transporte público \hspace{0.5mm} ( ) Táxi/Uber \hspace{0.5mm} ( ) Bicicleta \hspace{0.5mm} ( ) Não utiliza

\vspace{3mm}

**Tempo gasto diariamente em trânsito (em horas)**: _________

\vspace{3mm}

**Atividade física semanal (em horas)**: _________

\vspace{3mm}

**Tempo gasto por dia com o celular na mão (exceto ligações)**: _________

\vspace{3mm}

**Como você classifica a sua alimentação**: ( ) Péssima \hspace{0.5mm} ( ) Ruim \hspace{0.5mm} ( ) Regular \hspace{0.5mm} ( ) Boa \hspace{0.5mm} ( ) Ótima

\vspace{0.8cm}

**Esporte**: _____________________________

\vspace{3mm}

**Time (futebol)**: _____________________________

\vspace{3mm}

**Escritor**: _____________________________

\vspace{3mm}

**Livro**: _____________________________

\vspace{3mm}

**Estilo musical**: _____________________________

\vspace{3mm}

**Música**: _____________________________

\vspace{3mm}

**Diretor de cinema**: _____________________________

\vspace{3mm}

**Filme**: _____________________________










