---
title: "Lista de exercícios 1 - Entregar dia 13/01"
output: pdf_document
---

1. Classifique cada uma das variáveis abaixo como qualitativa nominal, qualitativa ordinal, quantitativa discreta ou quantitativa contínua.

a) Salários dos empregados de uma indústria.
b) Opinião de consumidores sobre determinado produto.
c) Número de respostas certas de alunos num teste com dez itens.
d) Temperatura diária da cidade de Rio Branco (AC).
e) Porcentagem da receita de municípios aplicada em educação.
f) Número de gols sofridos pelo SPFC no próximo jogo contra o Corinthians.
g) Candidato a prefeito preferido para as próximas eleições.
h) Resultado de um exame realizado para detectar uma determinada doença.

2. Sendo $\bar{x} = \frac{\sum_{i=1}^n x_i}{n}$, mostre que:

a) $\sum_{i=1}^n (x_i - \bar{x}) = 0$;
b) $\sum_{i=1}^n (x_i - \bar{x})^2 = \sum_{i=1}^n x_i^2 - n\bar{x}^2$.

3. O que acontece com a mediana, a média e o desvio padrão de um conjunto de dados quando:

a) cada observação é multiplicada por 2?
b) soma-se 10 a cada observação?
c) subtrai-se a média geral $\bar{x}$ de cada observação?
d) de cada observação subtrai-se $\bar{x}$ e divide-se pelo desvio padrão dp(x)?


4. Temos, a seguir, o número de gols pró dos 20 times de futebol que disputaram as últimas duas edições do Campeonato Brasileiro.

\centering

2015: 71 65 52 53 39 53 59 44 60 43 41 45 40 34 31 36 38 28 39 26

2014: 67 59 53 49 51 61 36 43 42 46 36 38 37 42 39 34 37 31 31 28

a) Encontre o mínimo, o primeiro quartil, a mediana, o terceiro quartil, o máximo e a distância interquartil.

b) Esboce (no mesmo gráfico) os boxplots. Analise o gráfico.