---
title: "Medidas resumo"
author: "William Nilson de Amorim"
date: "Verão 2017"
output: 
  ioslides_presentation:
    mathjax: "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    self_contained: true
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(pander)
library(ggplot2)
library(dplyr)
library(magrittr)
library(lubridate)
library(vcd)
panderOptions("table.style", "rmarkdown")
```

## Frequência e proporção {.build}

A <b>frequência absoluta</b> ($n_i$) representa o número de observações em uma determinada categoria ou valor da variável.

A <b>frequência relativa</b> ou <b>proporção</b> é a razão entre a frequência absoluta e o total de observações ($n$).

<div class="red">Quando utilizar essas medidas?</div>

## Medidas de posição {.build}

<b>Média</b>: soma das observações dividida pelo total de observações.

\vspace{3mm}

\[
\frac{\sum_{i=1}^{n}X_i}{n} = \frac{X_1 + X_2 + ... + X_n}{n}
\]

<div class="red">Quando utilizar a média?</div>

<div class="red">Por que dividir por $n$?</div>

<div class="red">Qual cuidado devemos ter ao utilizar a média como medida resumo? </div>
    
## Medidas de posição {.build}

<b>Mediana</b>: observação que ocupa a posição central dos dados ordenados.

Exemplo 1: 3 7 10 5 2 1 1

Exemplo 2: 15 3 2 0 9 17

<div class="red"> Quando utilizar a mediana? </div">

## Medidas de posição {.build}

<b> Quantis</b>: observação que deixa uma determinada proporção das observações abaixo dela quando o conjunto de dados está ordenado.

Exemplo 1: o quantil 10 ($q_{10}$) deixa 10% das observações ordenadas abaixo de si.

Exemplo 2: o quantil 80 ($q_{80}$) deixa 80% das observações ordenadas abaixo de si.

Em geral, o quantil p ($q_p$) deixa p% das observações ordenas abaixo de si.

## Medidas de posição

Quartis: 
    
    - Primeiro quartil (Q1): quantil 25
    - Segundo quartil (Q2): quantil 50 = mediana
    - Terceiro quartil (Q3): quantil 75
    - Quarto quartil (Q4): quantil 100 = máximo

## Medidas de posição {.build}

<b> Moda</b>: observação mais frequente do conjunto de observações.

<div class="red"> Quando utilizar a moda?

Qual o problema de utilizarmos apenas medidas de posição para resumir um conjunto de dados? </div>

## Medidas de dispersão {.build}

<b>Variância</b>: desvio quadrático médio em torno da média.

Construção da variância:

\[
\frac{\sum_{i=1}^{n}(X_i - \bar{X})^2}{n}
\]

<b>Desvio-padrão</b>: raiz quadrada da variância.

\[
\sqrt{\frac{\sum_{i=1}^{n}(X_i - \bar{X})^2}{n}}
\]

<div class="red">Por que utilizar o desvio-padrão?</div>


## Medidas de associação {.build}

<div class="red">
O que é a associação entre variáveis aleatórias?
</div>

Associação entre variáveis categóricas: veremos no fim do curso.

Associação entre variáveis quantitativas: coeficiente de correlação de Pearson.

Outros coeficientes de correlação: Spearman, Kendall.

## Medidas de associação

Coeficiente de correlação de Pearson

\vspace{3mm}

\[
\frac{1}{n}\sum_{i=1}^{n}\left(\frac{X_i - \bar{X}}{DP(X)}\right) \left(\frac{Y_i - \bar{Y}}{DP(Y)}\right)
\]
















